Experimental annotations class
NKI-AI/dlup pull request #70
Opened 2022-05-24 21:50 UTC by jonasteuwen

This is an experimental annotation class support. Ajey has some experience, could you add examples of how you use it with GeoJSON (Shapely output)? I'll do some for the ASAP class, and we can discuss if this API is what we want.

2022-05-25 09:01 UTC, YoniSchirris requested changes
Can we also add some examples of annotations in several formats to see how the annotations should look?

Can we add some example script to know how we can use this for several use cases?

2022-05-26 23:10 UTC, jonasteuwen commented on dlup/_experimental_annotation.py
> +_ASAP_TYPES = {
The tool made in Nijmegen https://github.com/computationalpathologygroup/ASAP. E.g. data for tiger and camelyon is provided in this format.

2022-05-26 23:11 UTC, jonasteuwen commented on dlup/_experimental_annotation.py
> +        return [_get_bbox(_) for _ in data]
Sure, can do.

2022-05-26 23:12 UTC, jonasteuwen commented on dlup/_experimental_annotation.py
> +    """Class to hold the annotations of all labels specific label for a whole slide image"""
All labels in this case. I'll elaborate in the string.

2022-05-26 23:12 UTC, jonasteuwen commented on dlup/_experimental_annotation.py
> +class SlideAnnotations:
Indeed. It will need to be renamed.

2022-05-26 23:13 UTC, jonasteuwen commented on dlup/_experimental_annotation.py
> +        pass
Yes.

2022-05-26 23:14 UTC, jonasteuwen commented on dlup/_experimental_annotation.py
> +
Yes, that's definitely a better idea!

2022-05-26 23:14 UTC, jonasteuwen commented on dlup/_experimental_annotation.py
> +    def read_region(
Because you want to read a part of the whole annotation - same as with reading a region from an image.

2022-05-26 23:15 UTC, jonasteuwen commented on dlup/_experimental_annotation.py
> +        raise RuntimeError(f"Not a supported shapely type: {shapely_type}")
Not sure, remainder of trying to figure out the proper API. I'll work a bit on it.

2022-05-26 23:15 UTC, jonasteuwen commented
Thanks @YoniSchirris. @AjeyPaiK can you give a multiclass label example how you use it? I'll give one for the ASAP types - the API should be similar.

2022-05-26 23:59 UTC, jonasteuwen commented
I do think there should be support for an "ROI" label, in the ASAP setting, you have a single file, so you can add a key "ROI" so these things get treated on a different footing than the standard annotations. How would you do that in your case @AjeyPaiK?

2022-05-27 00:29 UTC, jonasteuwen commented
I do think there should be support for an "ROI" label, in the ASAP setting, you have a single file, so you can add a key "ROI" so these things get treated on a different footing than the standard annotations. How would you do that in your case @AjeyPaiK?

2022-05-27 01:41 UTC, jonasteuwen commented
I have tried to make the code a bit more elegant. Also the `read_region` function is there in case we would have tiff's or so with annotations, those can be read as `SlideImage`, and can be used in the same way as annotations. Currently there is no container object yet that would allow the use of mixed annotations. Do you see any use case? E.g. points in a geojson and segmentations in a tiff?

2022-05-29 21:02 UTC, AjeyPaiK commented
> I do think there should be support for an "ROI" label, in the ASAP setting, you have a single file, so you can add a key "ROI" so these things get treated on a different footing than the standard annotations. How would you do that in your case @AjeyPaiK?

Currently, I haven't found a use-case for annotation type "ROI". However, the existing implementation for `from_geojson` should already cater to it as long as the "ROI" annotations are parsed as shapely objects (`MultiPolygon`, `Polygon`). This function is already capable of parsing Brush, Polygon types of annotation. Although, every type of annotation (Brush, Polygon etc) corresponding to a single label should be in a single annotation file.

2022-05-29 21:34 UTC, AjeyPaiK commented on dlup/_experimental_annotation.py
> +        raise RuntimeError(f"Not a supported shapely type: {shapely_type}")
Thanks for the keen observation @YoniSchirris. This function helps us for two reasons:

1. The shapely objects are of different types but for all practical purposes, these types do not matter to us once they've been parsed properly. So, this function allows us to club different types of shapely objects into a single kind of annotation (for example, `MultiPolygon` and `Polygon` which are actually two different kinds of shapely objects can be treated as a single type `Annotation.POLYGON`.) 

2. Additionally, we also want to check if each shapely object being parsed from the annotation file is actually supported by our dataset class. So, we pass each and every polygon into this function. I had some trouble too understanding why exactly we need this function but I retained it with minimal changes [here](https://github.com/NKI-AI/dlup/commit/29f1ae9ab99f7bdcf817126255b77d6121cbebc6).

If there was no need to club two different shapely object types into one, we could directly infer them by checking if the object being parsed belongs to `AnnotationType.__members__ `. 

Also, I should've caught the discrepancy in the return types. In the current implementation, it should be `Union[str, AnnotationType]`.

This was a good catch and I think there is room for more improvement on how we handle the different annotation types.

2022-05-29 21:55 UTC, AjeyPaiK commented
> Thanks @YoniSchirris. @AjeyPaiK can you give a multiclass label example how you use it? I'll give one for the ASAP types - the API should be similar.

So far, I haven't implemented the multiclass example. To do this, I will have to first make changes to the slidescore-api which currently [downloads](https://github.com/NKI-AI/slidescore-api/blob/bbcac96299cda2d4160912edf7a0d63090c020a0/slidescore_api/utils/annotations.py#L317-L323) annotations of single labels from slidescore. Currently, all of my subsequent implementations depends on this. Will work on this this week.

2022-05-29 22:32 UTC, jonasteuwen commented
Hey @AjeyPaiK it should already read a list of paths for different labels. So that should be fine and supported by the SlideScore API. Can you show an example with tumor mask *and* while tissue label?

2022-05-29 22:33 UTC, jonasteuwen commented
Current work flow for ROI would be the following: add in a ROI as label, then create the annotation class, and call 'bbox' on the ROI label. Keep the ROI label in there, because augmentations might rotate it, and then use the ROI to create a dataset only around those labels. This is supported in the current `MultiscaleDataset`. So I don't think it requires more work.

2022-05-29 22:36 UTC, jonasteuwen commented on dlup/_experimental_annotation.py
> +        raise RuntimeError(f"Not a supported shapely type: {shapely_type}")
@AjeyPaiK Yes, you got that right. I think the return type should always be `AnnotationType`. We don't have multi polygon, which are basically a group of polygons, we would only return a bunch of polygons. Have not yet seen a use case for us where the distinction is required as multi polygon are just two regions of the same thing.

2022-05-29 22:39 UTC, AjeyPaiK commented
> Hey @AjeyPaiK it should already read a list of paths for different labels. So that should be fine and supported by the SlideScore API. Can you show an example with tumor mask _and_ while tissue label?

Do you mean with tumor mask and with tissue label together in one go?

2022-05-29 22:43 UTC, AjeyPaiK commented on dlup/_experimental_annotation.py
> +        raise RuntimeError(f"Not a supported shapely type: {shapely_type}")
No, the distinction is not necessary since there is a for loop running which will iterate over all these shapes anyway. 😁

2022-05-31 01:28 UTC, jonasteuwen commented
Okay @AjeyPaiK @YoniSchirris so the output is now replaced with our own `Point` and `Polygon` class, which have the same behavior as their Shapely analogs, but they have `label` attribute and a `type` which is of `AnnotationType`. It does require shapely 2.0, which is not yet upstream, so you must install it like:

`pip install git+github.com/shapely/shapely` (after `pip uninstall shapely`)

2022-05-31 21:41 UTC, AjeyPaiK requested changes
Thanks for the very elegant implementation of the whole slide image annotation class. 

I have some suggestion that we need to put in place as failsafe to make sure this class is robust to bad annotations.

While creating an example for the `geo_json` type annotations, I had a bad polygon in my file (with `polygon.is_valid() = False`) and the `read_region()` function failed when I tried to read that annotation. The shapely library threw a self intersection error.

I looked at the code and I realised, we are not checking whether or not the polygons that are being read from the annotation files are valid. Specifically, before we do anything else in the following for loop below, we need to check if our `annotation` is valid. If not, it should be made valid and then the remaining steps should be executed.

https://github.com/NKI-AI/dlup/blob/2eca002b805db14251d0e9297584e6a0421efce3/dlup/_experimental_annotation.py#L371-L376

2022-05-31 22:01 UTC, AjeyPaiK submitted a review, later dismissed

2022-05-31 22:34 UTC, AjeyPaiK commented
> 

I have now added an example for reading `geo_json` annotations using this implementation.

2022-06-01 15:13 UTC, merged